config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about'
  get 'homes/parent_top', to: 'homes#parent_top'
  get 'homes/child_top', to: 'homes#child_top'
  get 'homes/giving_top', to: 'homes#giving_top'
  # session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/child_login',   to: 'child_sessions#new'
  post   '/child_login',   to: 'child_sessions#create'
  delete '/child_logout',  to: 'child_sessions#destroy'
  get    '/giving_login',   to: 'giving_sessions#new'
  post   '/giving_login',   to: 'giving_sessions#create'
  delete '/giving_logout',  to: 'giving_sessions#destroy'
  # resources
  resources :parents
  resources :children
  resources :givings
  resources :posts do
    resource :fins, only: [:create, :destroy]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :forbid_login_user
  def top
  end

  def about
  end

  def parent_top
  end

  def child_top
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<h1 class="headline pt-3">manaberuって何？</h1>
<div class="text">
  <div>manaberuとは色々なことを知るためのサービスです。</div>
  <p class="pt-4"><%=link_to "ホームに戻る", root_path, class:"link-green" %></p>
</div>

app/views/homes/child_top.html.erb
<div class="flex-container-btn">
  <div class="flex-item-btn">
    <%=link_to "アカウント作成", new_child_path, class: "link-white btn-circle-flat" %>
    <p class="text">初めての方はこちら</p>
  </div>
  <div class="flex-item-btn">
    <%=link_to "ログイン", child_login_path, class: "link-white btn-circle-flat" %>
    <p class="text">アカウントをお持ちの方</p>
  </div>
</div>

app/views/homes/giving_top.html.erb
<div class="flex-container-btn">
  <div class="flex-item-btn">
    <%=link_to "アカウント作成", new_giving_path, class: "link-white btn-circle-flat" %>
    <p class="text">初めての方はこちら</p>
  </div>
  <div class="flex-item-btn">
    <%=link_to "ログイン", giving_login_path, class: "link-white btn-circle-flat" %>
    <p class="text">アカウントをお持ちの方</p>
  </div>
</div>

app/views/homes/parent_top.html.erb
<div class="flex-container-btn">
  <div class="flex-item-btn">
    <%=link_to "学校登録", new_parent_path, class: "link-white btn-circle-flat" %>
    <p class="text">初めての方はこちら</p>
  </div>
  <div class="flex-item-btn">
    <%=link_to "ログイン", login_path, class: "link-white btn-circle-flat" %>
    <p class="text">アカウントをお持ちの方</p>
  </div>
</div>

app/views/homes/top.html.erb
<div class="top-image">
  <h1 class="home-top headline">manaberu</h1>
  <p class="paragraph"><%=link_to "manaberuって何？", homes_about_path, class:"link-top" %></p>
</div>
<div class="flex-container">
  <div class="flex-item"><%=link_to "教員はこちら", homes_parent_top_path, class:"btn-square link-white" %></div>
  <div class="flex-item"><%=link_to "生徒はこちら", homes_child_top_path, class:"btn-square link-white" %></div>
</div>