config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about'
  get 'homes/parent_top', to: 'homes#parent_top'
  get 'homes/child_top', to: 'homes#child_top'
  get 'homes/giving_top', to: 'homes#giving_top'
  # session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/child_login',   to: 'child_sessions#new'
  post   '/child_login',   to: 'child_sessions#create'
  delete '/child_logout',  to: 'child_sessions#destroy'
  get    '/giving_login',   to: 'giving_sessions#new'
  post   '/giving_login',   to: 'giving_sessions#create'
  delete '/giving_logout',  to: 'giving_sessions#destroy'
  # resources
  resources :parents
  resources :children
  resources :givings
  resources :posts do
    resource :fins, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :name, presence: true
  validates :youtube_url, presence: true
  validates :giving_id, presence: true
  has_many :fins, dependent: :destroy
  belongs_to :giving

  def finished?(child)
      fins.where(child_id: child.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user_giving.posts.build(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to giving_path(@post.giving)
  end

  private
   def post_params
     params.require(:post).permit(:content, :youtube_url, :name )
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post-form.html.erb
<%=form_with model: @post, local: true do |f| %>
<div class="form-group">
  <%=f.label :name %>
  <%=f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%=f.label :content %>
  <%=f.text_field :content, class: "form-control" %>
</div>
<div class="form-group">
  <%=f.label :youtube_url %>
  <%=f.text_field :youtube_url, class: "form-control" %>
</div>
<%=f.submit "送信", class:"btn btn-light"%>
<% end %>

app/views/posts/edit.html.erb
<div class="wrapper">
  <h1>授業編集</h1>
  <%=render 'posts/post-form'%>
</div>

app/views/posts/index.html.erb
<h1 class="headline pt-4">授業一覧</h1>
<table class="table">
  <tbody>
    <%@posts.each do |post| %>
    <tr>
      <td>
        <%=link_to post.name, post_path(post), class:"link-green"%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="wrapper">
  <h1>授業投稿</h1>
  <%=render 'posts/post-form'%>
</div>

app/views/posts/show.html.erb
<h1 class="headline pt-4"><%=@post.name%></h1>
<div class="video">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<div class="post-content">
  動画説明
  <div>
    <%=@post.content%>
  </div>
</div>
<% if @post.giving == current_user_giving %>
<div class="flex-container">
  <div class="pr-3"><%=link_to "編集", edit_post_path(@post),class:"link-green"%></div>
  <div class="pl-3"><%=link_to "削除", post_path(@post), {method: :delete, class:"link-red", data:{confirm: '本当に削除しますか？'}} %></div>
</div>
<% end %>
<% if child_logged_in? %>
<div class="icon-text">
   <% if @post.finished?(current_user_child) %>
     <%=link_to post_fins_path(@post), {method: :delete, class:"text-success text-decoration-none"} do %>
       <i class="far fa-check-square icon"></i>
       <p>OK!</p>
     <% end %>
   <% else %>
     <%=link_to post_fins_path(@post), {method: :post, class:"text-danger text-decoration-none"} do %>
       <i class="far fa-check-square icon"></i>
       <p>動画をみたらチェック！</p>
       <% end %>
   <% end %>
   </div>
<% end %>