config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about'
  get 'homes/parent_top', to: 'homes#parent_top'
  get 'homes/child_top', to: 'homes#child_top'
  get 'homes/giving_top', to: 'homes#giving_top'
  # session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/child_login',   to: 'child_sessions#new'
  post   '/child_login',   to: 'child_sessions#create'
  delete '/child_logout',  to: 'child_sessions#destroy'
  get    '/giving_login',   to: 'giving_sessions#new'
  post   '/giving_login',   to: 'giving_sessions#create'
  delete '/giving_logout',  to: 'giving_sessions#destroy'
  # resources
  resources :parents
  resources :children
  resources :givings
  resources :posts do
    resource :fins, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :nickname, presence: true
  validates :parent_id, presence: true
  has_secure_password
  has_one_attached :avatar
  has_many :fins, dependent: :destroy
  has_many :fin_posts, through: :fins, source: :post, dependent: :destroy
  belongs_to :parent

  def icon_avatar
    # avatar.variant(resize: '40x40').processed
    avatar.variant(combine_options: { resize: '40x40^', crop: '40x40+0+0', gravity: :center }).processed
  end
end

app/models/fin.rb
class Fin < ApplicationRecord
  belongs_to :post
  belongs_to :child
end

app/models/giving.rb
class Giving < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_many :posts, dependent: :destroy
  has_secure_password
  has_one_attached :avatar

  def giving_avatar
    avatar.variant(combine_options: { resize: '40x40^', crop: '40x40+0+0', gravity: :center }).processed
  end
end

app/models/parent.rb
class Parent < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  has_many :children, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :name, presence: true
  validates :youtube_url, presence: true
  validates :giving_id, presence: true
  has_many :fins, dependent: :destroy
  belongs_to :giving

  def finished?(child)
      fins.where(child_id: child.id).exists?
  end
end

app/controllers/fins_controller.rb
class FinsController < ApplicationController

  def create
    fin = current_user_child.fins.build(post_id: params[:post_id])
    fin.save
    redirect_to post_path(id: params[:post_id])
  end

  def destroy
    fin = Fin.find_by(post_id: params[:post_id], child_id: current_user_child.id)
    fin.destroy
    redirect_to post_path(id: params[:post_id])
  end
end

app/controllers/givings_controller.rb
class GivingsController < ApplicationController
  before_action :forbid_login_user, only:[:new, :create]
  def new
    @giving = Giving.new
  end

  def create
    @giving = Giving.new(giving_params)
    if @giving.avatar.attach(params[:giving][:avatar]) && @giving.save
      giving_login @giving
      flash[:notice] = "ユーザー登録完了"
      redirect_to giving_path(@giving)
    else
      render 'new'
    end
  end

  def index
    @givings = Giving.all.order(created_at: :desc)
  end

  def show
    @giving = Giving.find(params[:id])
    @posts = @giving.posts
  end

  def edit
    @giving = Giving.find(params[:id])
  end

  def update
    @giving = Giving.find(params[:id])
    if @giving.update(giving_params)
      flash[:notice] = "ユーザー編集完了"
      redirect_to giving_path(@giving)
    else
      render 'edit'
    end
  end

  def destroy
    @giving = Giving.find(params[:id])
    giving_logout
    @giving.destroy
    flash[:notice] = "ユーザー削除完了"
    redirect_to root_path
  end

  private
   def giving_params
     params.require(:giving).permit(:name, :email, :password, :password_confirmation, :avatar)
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :forbid_login_user
  def top
  end

  def about
  end

  def parent_top
  end

  def child_top
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :forbid_login_user, only:[:new, :create]
  def index
    @parents = Parent.all.order(created_at: :desc)
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.new(parent_params)
    if @parent.save
      parent_login @parent
      flash[:notice] = "ユーザー登録完了"
      redirect_to parent_path(@parent)
    else
      render 'new'
    end
  end

  def edit
    @parent = Parent.find(params[:id])
  end

  def update
    @parent = Parent.find(params[:id])
    if @parent.update(parent_params)
      flash[:notice] = "ユーザー編集完了"
      redirect_to parent_path(@parent)
    else
      render 'edit'
    end
  end

  def destroy
    @parent = Parent.find(params[:id])
    @parent.destroy
    parent_logout
    flash[:notice] = "ユーザー削除完了"
    redirect_to root_path
  end

  private
   def parent_params
     params.require(:parent).permit(:name, :email, :password, :password_confirmation)
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user_giving.posts.build(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to giving_path(@post.giving)
  end

  private
   def post_params
     params.require(:post).permit(:content, :youtube_url, :name )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/child_sessions_helper.rb
module ChildSessionsHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/fins_helper.rb
module FinsHelper
end

app/helpers/givings_helper.rb
module GivingsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # parent-----------------------
  def parent_login(parent)
    session[:parent] = parent.id
  end

  def current_user_parent
    if session[:parent]
      @current_user_parent ||= Parent.find_by(id: session[:parent])
    end
  end

  def parent_logged_in?
    !current_user_parent.nil?
  end

  def parent_logout
    session.delete(:parent)
    @current_user_parent = nil
  end

  # child------------------------
  def child_login(child)
    session[:child] = child.id
  end

  def current_user_child
    if session[:child]
      @current_user_child ||= Child.find_by(id: session[:child])
    end
  end

  def child_logged_in?
    !current_user_child.nil?
  end

  def child_logout
    session.delete(:child)
    @current_user_child = nil
  end

  # giving-----------------------

  def giving_login(giving)
    session[:giving] = giving.id
  end

  def current_user_giving
    if session[:giving]
      @current_user_giving ||= Giving.find_by(id: session[:giving])
    end
  end

  def giving_logged_in?
    !current_user_giving.nil?
  end

  def giving_logout
    session.delete(:giving)
    @current_user_giving = nil
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success">
  <%=flash[:notice]%>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <h1><%=link_to "manaberu",homes_about_path, class:"link-green" %></h1>
  <% if parent_logged_in? %>
  <ul class="gnav">
    <li><%=link_to current_user_parent.name, parent_path(current_user_parent), class: "link-green" %></li>
    <li>
      <a href="#" ontouchsrart=""><span>メニュー</span></a>
      <ul>
        <li><%=link_to "ユーザー編集", edit_parent_path(current_user_parent), class: "link-green" %></li>
        <li><%=link_to "ログアウト", logout_path, {method: :delete , class: "link-green"} %></li>
      </ul>
    </li>
  </ul>
  <% elsif child_logged_in? %>
  <ul class="gnav">
    <li><%=link_to current_user_child.nickname, child_path(current_user_child), class: "link-green" %></li>
    <li>
      <a href="#" ontouchsrart=""><span>メニュー</span></a>
      <ul>
        <li><%=link_to "授業一覧", posts_path %></li>
        <li><%=link_to "先生一覧", givings_path %></li>
        <li><%=link_to "ユーザー編集", edit_child_path(current_user_child), class: "link-green" %></li>
        <li><%=link_to "ログアウト", child_logout_path, {method: :delete , class: "link-green"} %></li>
      </ul>
    </li>
  </ul>
  <% elsif giving_logged_in? %>
  <ul class="gnav">
    <li><%=link_to current_user_giving.name, giving_path(current_user_giving), class: "link-green" %></li>
    <li>
      <a href="#" ontouchsrart=""><span>メニュー</span></a>
      <ul>
        <li><%=link_to "授業を作る", new_post_path, class: "link-green" %></li>
        <li><%=link_to "ユーザー編集", edit_giving_path(current_user_giving), class: "link-green" %></li>
        <li><%=link_to "ログアウト", giving_logout_path, {method: :delete , class: "link-green"} %></li>
      </ul>
    </li>
  </ul>
  <% else %>
  <ul class="gnav">
    <li>
      <a href="#" ontouchsrart="">メニュー</a>
      <ul>
        <li><%=link_to "先生はこちら", homes_giving_top_path %></li>
      </ul>
    </li>
  </ul>
  <% end %>
</header>

<div class="mar"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Manaberu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="b-body">
      <%=render 'layouts/header'%>
      <%=render 'layouts/flash'%>
      <%= yield %>
    </div>

    <footer>
      <div class="footer-container">
        manaberu
      </div>
    </footer>
  </body>
</html>